# Generated by Django 5.2.5 on 2025-09-06 12:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanmind', '0002_alter_board_owner_alter_comment_author_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='members',
            field=models.ManyToManyField(related_name='board_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
