# Generated by Django 5.2.5 on 2025-09-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanmind', '0003_alter_board_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='created_by',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(auto_now=True),
        ),
    ]
