# Generated by Django 5.2.6 on 2025-09-18 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanmind', '0009_alter_task_due_date_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.date(2025, 9, 18)),
        ),
    ]
