# Generated by Django 5.2.5 on 2025-09-22 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanmind', '0011_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.date(2025, 9, 22)),
        ),
    ]
