# Generated by Django 5.2.6 on 2025-09-26 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanmind', '0014_alter_task_due_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assignee_id',
            new_name='assignee',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='reviewer_id',
            new_name='reviewer',
        ),
    ]
