# Generated by Django 5.2.5 on 2025-08-27 18:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KanMind_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='name',
        ),
        migrations.AddField(
            model_name='column',
            name='assigned_tasks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='KanMind_App.task'),
        ),
        migrations.AddField(
            model_name='column',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='board',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='boards', to='KanMind_App.member'),
        ),
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='column',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KanMind_App.board'),
        ),
        migrations.AlterField(
            model_name='member',
            name='joined_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(),
        ),
    ]
