# Generated by Django 5.2.5 on 2025-08-27 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KanMind_App', '0002_remove_column_name_column_assigned_tasks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='assigned_tasks',
        ),
        migrations.RemoveField(
            model_name='column',
            name='board',
        ),
        migrations.AddField(
            model_name='board',
            name='done',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='done', to='KanMind_App.column'),
        ),
        migrations.AddField(
            model_name='board',
            name='in_progress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_progress', to='KanMind_App.column'),
        ),
        migrations.AddField(
            model_name='board',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='KanMind_App.column'),
        ),
        migrations.AddField(
            model_name='board',
            name='todo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todo', to='KanMind_App.column'),
        ),
        migrations.AlterField(
            model_name='board',
            name='members',
            field=models.ManyToManyField(related_name='boards', to='KanMind_App.member'),
        ),
        migrations.AlterField(
            model_name='board',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='KanMind_App.member'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KanMind_App.column'),
        ),
    ]
