# Generated by Django 5.2.5 on 2025-08-27 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KanMind_App', '0003_remove_column_assigned_tasks_remove_column_board_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='board',
        ),
        migrations.AddField(
            model_name='board',
            name='assigned_tasks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='KanMind_App.task'),
        ),
    ]
