# Generated by Django 5.2.5 on 2025-08-30 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KanMind_App', '0004_remove_task_board_board_assigned_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='assigned_tasks',
        ),
        migrations.RemoveField(
            model_name='board',
            name='done',
        ),
        migrations.RemoveField(
            model_name='board',
            name='in_progress',
        ),
        migrations.RemoveField(
            model_name='board',
            name='review',
        ),
        migrations.RemoveField(
            model_name='board',
            name='todo',
        ),
        migrations.RemoveField(
            model_name='column',
            name='title',
        ),
        migrations.AddField(
            model_name='column',
            name='board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='KanMind_App.board'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='column',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='column',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='column',
            name='type',
            field=models.CharField(blank=True, choices=[('TODO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('REVIEW', 'Review'), ('DONE', 'Done')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='KanMind_App.board'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='low', max_length=10),
        ),
    ]
